Watching for file changes with StatReloader
[15/May/2019 20:16:40] "GET / HTTP/1.1" 200 2053
[15/May/2019 20:16:40] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 20:16:40] "GET /static/css/home.css HTTP/1.1" 304 0
[15/May/2019 20:19:34] "GET / HTTP/1.1" 200 2022
[15/May/2019 20:19:34] "GET /static/css/base.css HTTP/1.1" 200 1776
[15/May/2019 20:19:34] "GET /static/css/home.css HTTP/1.1" 304 0
[15/May/2019 20:20:45] "GET / HTTP/1.1" 200 2022
[15/May/2019 20:20:45] "GET /static/css/base.css HTTP/1.1" 200 1816
[15/May/2019 20:22:57] "GET / HTTP/1.1" 200 2050
[15/May/2019 20:22:57] "GET /static/css/base.css HTTP/1.1" 200 1930
[15/May/2019 20:22:57] "GET /static/css/home.css HTTP/1.1" 304 0
[15/May/2019 20:25:20] "GET / HTTP/1.1" 200 2050
[15/May/2019 20:25:20] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 20:25:20] "GET /static/css/home.css HTTP/1.1" 304 0
[15/May/2019 20:26:24] "GET / HTTP/1.1" 200 2123
[15/May/2019 20:26:24] "GET /static/css/base.css HTTP/1.1" 200 1895
[15/May/2019 20:26:37] "GET / HTTP/1.1" 200 2123
[15/May/2019 20:26:37] "GET /static/css/base.css HTTP/1.1" 200 1915
[15/May/2019 20:29:15] "GET / HTTP/1.1" 200 2123
[15/May/2019 20:29:15] "GET /static/css/base.css HTTP/1.1" 200 1944
[15/May/2019 20:29:15] "GET /static/css/home.css HTTP/1.1" 304 0
[15/May/2019 20:29:25] "GET / HTTP/1.1" 200 2123
[15/May/2019 20:29:25] "GET /static/css/base.css HTTP/1.1" 200 1943
[15/May/2019 20:29:36] "GET / HTTP/1.1" 200 2123
[15/May/2019 20:29:36] "GET /static/css/base.css HTTP/1.1" 200 1942
[15/May/2019 20:30:10] "GET / HTTP/1.1" 200 2123
[15/May/2019 20:30:10] "GET /static/css/base.css HTTP/1.1" 200 1956
[15/May/2019 20:30:19] "GET / HTTP/1.1" 200 2123
[15/May/2019 20:30:19] "GET /static/css/base.css HTTP/1.1" 200 1956
[15/May/2019 20:32:33] "GET / HTTP/1.1" 200 2147
[15/May/2019 20:32:33] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 20:32:33] "GET /static/css/home.css HTTP/1.1" 304 0
[15/May/2019 20:33:06] "GET / HTTP/1.1" 200 2147
[15/May/2019 20:33:06] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 20:34:04] "GET / HTTP/1.1" 200 2147
[15/May/2019 20:34:04] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 20:35:52] "GET / HTTP/1.1" 200 2223
[15/May/2019 20:35:52] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 20:35:52] "GET /static/css/home.css HTTP/1.1" 304 0
[15/May/2019 20:37:06] "GET / HTTP/1.1" 200 2246
[15/May/2019 20:37:06] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 20:37:52] "GET / HTTP/1.1" 200 2327
[15/May/2019 20:37:52] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 20:39:13] "GET / HTTP/1.1" 200 2327
[15/May/2019 20:39:13] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 20:39:13] "GET /static/css/home.css HTTP/1.1" 304 0
[15/May/2019 20:39:27] "GET / HTTP/1.1" 200 2333
[15/May/2019 20:39:35] "GET / HTTP/1.1" 200 2327
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/scode/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/scode/.local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/scode/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[0](_exception[1]).with_traceback(_exception[2])
  File "/home/scode/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/scode/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/scode/.local/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/scode/.local/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/scode/.local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/scode/.local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/scode/.local/lib/python3.6/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/scode/.local/lib/python3.6/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/scode/.local/lib/python3.6/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/scode/.local/lib/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/scode/.local/lib/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/scode/.local/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/scode/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 20, in <module>
    ) from err
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?

/home/scode/Capstone_Design/src/Django/scode/scode/views.py changed, reloading.
Watching for file changes with StatReloader
[15/May/2019 22:06:49] "GET / HTTP/1.1" 200 2327
[15/May/2019 22:06:49] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 22:06:49] "GET /static/css/home.css HTTP/1.1" 304 0
Unhandled exception in thread started by <function wrapper at 0x7f63d3073e60>
Traceback (most recent call last):
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/scode/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^professor/', include(('judge.urls', 'judge'), namespace='judge')).
NameError: name 'include' is not defined
Unhandled exception in thread started by <function wrapper at 0x7efdd1c67e60>
Traceback (most recent call last):
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/scode/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^professor/', include(('judge.urls', 'judge'), namespace='judge')).
NameError: name 'include' is not defined
Unhandled exception in thread started by <function wrapper at 0x7f5c0b32be60>
Traceback (most recent call last):
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/scode/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^professor/', include(('judge.urls', 'judge'), namespace='judge')).
AttributeError: 'RegexURLResolver' object has no attribute 'url'
Unhandled exception in thread started by <function wrapper at 0x7f41ca66ae60>
Traceback (most recent call last):
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/scode/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^professor/', include(('judge.urls', 'judge'), namespace='judge')).
AttributeError: 'RegexURLResolver' object has no attribute 'url'
Error: That port is already in use.
[15/May/2019 23:26:29] "GET / HTTP/1.1" 200 2327
[15/May/2019 23:26:29] "GET /static/css/base.css HTTP/1.1" 304 0
[15/May/2019 23:26:29] "GET /static/css/home.css HTTP/1.1" 304 0
[15/May/2019 23:26:33] "GET /professor HTTP/1.1" 301 0
Internal Server Error: /professor/
Traceback (most recent call last):
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: as_view() takes exactly 1 argument (2 given)
[15/May/2019 23:26:33] "GET /professor/ HTTP/1.1" 500 62630
[16/May/2019 17:55:50] "GET / HTTP/1.1" 200 2327
[16/May/2019 17:55:50] "GET /static/css/base.css HTTP/1.1" 200 1956
[16/May/2019 17:55:50] "GET /static/css/home.css HTTP/1.1" 200 163
Error: That port is already in use.
[17/May/2019 14:08:06] "GET / HTTP/1.1" 200 2327
[17/May/2019 14:08:06] "GET /static/css/base.css HTTP/1.1" 304 0
[17/May/2019 14:08:06] "GET /static/css/home.css HTTP/1.1" 304 0
[17/May/2019 14:47:50] "GET / HTTP/1.1" 200 2327
Unhandled exception in thread started by <function wrapper at 0x7f87505d6e60>
Traceback (most recent call last):
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/scode/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/scode/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/scode/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/scode/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/home/scode/.local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/scode/Capstone_Design/src/Django/scode/judge/urls.py", line 4, in <module>
    from judge.views import ProfessorMainLV
  File "/home/scode/Capstone_Design/src/Django/scode/judge/views.py", line 15, in <module>
    class ProfessorMainLV(View):
NameError: name 'View' is not defined
[18/May/2019 08:15:14] "GET /judge/professor/subject/result HTTP/1.1" 200 1530
[18/May/2019 08:15:14] "GET /static/css/base.css HTTP/1.1" 304 0
[18/May/2019 08:15:15] "GET /static/img/hallym_logo.png HTTP/1.1" 304 0
[18/May/2019 08:15:16] "GET /judge/professor/subject/result HTTP/1.1" 200 1530
[18/May/2019 08:15:18] "GET /judge/student/ HTTP/1.1" 200 1514
[18/May/2019 08:15:21] "GET /judge/student/ HTTP/1.1" 200 1514
[18/May/2019 08:15:22] "GET /judge/student/ HTTP/1.1" 200 1514
[18/May/2019 08:15:24] "GET /judge/student/ HTTP/1.1" 200 1514
[18/May/2019 08:15:25] "GET /judge/student/ HTTP/1.1" 200 1514
[18/May/2019 08:15:30] "GET /judge/professor/subject HTTP/1.1" 200 1532
[18/May/2019 08:15:32] "GET /judge/student/ HTTP/1.1" 200 1514
[18/May/2019 08:15:33] "GET /judge/student/ HTTP/1.1" 200 1514
[18/May/2019 08:16:51] "GET /judge/student/ HTTP/1.1" 200 1535
[18/May/2019 08:16:53] "GET /judge/student/ HTTP/1.1" 200 1535
[18/May/2019 08:16:54] "GET /judge/student/std_subject HTTP/1.1" 200 1535
[18/May/2019 08:16:56] "GET /judge/student/std_assign HTTP/1.1" 200 1535
[18/May/2019 08:19:03] "GET /judge/student/ HTTP/1.1" 200 1535
[18/May/2019 08:19:05] "GET /judge/student/std_subject HTTP/1.1" 200 1535
[18/May/2019 08:19:06] "GET /judge/student/std_assign HTTP/1.1" 200 1535
[18/May/2019 08:19:18] "GET /judge/student/ HTTP/1.1" 200 1535
[18/May/2019 08:19:42] "GET /judge/student/ HTTP/1.1" 200 1535
[18/May/2019 08:20:01] "GET /judge/student/std_subject HTTP/1.1" 200 1535
[18/May/2019 08:20:02] "GET /judge/student/std_assign HTTP/1.1" 200 1535
[18/May/2019 08:20:04] "GET /judge/professor/subject HTTP/1.1" 200 1553
[18/May/2019 08:20:07] "GET /judge/student/ HTTP/1.1" 200 1535
[18/May/2019 08:22:46] "GET /judge/student/ HTTP/1.1" 200 1535
[18/May/2019 08:22:47] "GET /judge/student/ HTTP/1.1" 200 1535
[18/May/2019 08:22:49] "GET /judge/student/std_subject HTTP/1.1" 200 1535
[18/May/2019 08:22:51] "GET /judge/student/std_assign HTTP/1.1" 200 1535
[18/May/2019 08:24:49] "GET /judge/student/std_assign HTTP/1.1" 200 1531
[18/May/2019 08:24:51] "GET /judge/student/std_subject HTTP/1.1" 200 1557
[18/May/2019 08:24:53] "GET /judge/student/std_assign HTTP/1.1" 200 1531
[18/May/2019 08:26:05] "GET /judge/student/ HTTP/1.1" 200 1551
[18/May/2019 08:26:06] "GET /judge/student/std_subject HTTP/1.1" 200 1557
[18/May/2019 08:26:07] "GET /judge/student/std_assign HTTP/1.1" 200 1531
[18/May/2019 08:26:18] "GET /judge/student/ HTTP/1.1" 200 1551
[18/May/2019 08:26:20] "GET /judge/student/std_subject HTTP/1.1" 200 1557
[18/May/2019 09:38:03] "GET / HTTP/1.1" 200 1705
Invalid HTTP_HOST header: u'83796c64d2a0:8000'. You may need to add u'83796c64d2a0' to ALLOWED_HOSTS.
[18/May/2019 10:48:43] "HEAD /robots.txt HTTP/1.0" 400 58562
Invalid HTTP_HOST header: '210.115.229.133:80'. You may need to add u'210.115.229.133' to ALLOWED_HOSTS.
[18/May/2019 11:04:26] "GET / HTTP/1.1" 400 58831
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add u'www.baidu.com' to ALLOWED_HOSTS.
[18/May/2019 11:55:30] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 400 59301
[18/May/2019 13:47:01] "GET /judge/student/std_subject HTTP/1.1" 200 1557
[18/May/2019 13:47:01] "GET /static/css/base.css HTTP/1.1" 304 0
[18/May/2019 13:47:01] "GET /static/img/hallym_logo.png HTTP/1.1" 304 0
Unhandled exception in thread started by <function wrapper at 0x7f03a3247488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 4, in <module>
    from judge.views import *
  File "/Capstone_Design/src/Django/scode/judge/views.py", line 47
    return render(request, 'judge/student/student_assignment.html', {'forms' : form})
SyntaxError: 'return' outside function
Unhandled exception in thread started by <function wrapper at 0x7f0b02e83488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 4, in <module>
    from judge.views import *
  File "/Capstone_Design/src/Django/scode/judge/views.py", line 47
    return render(request, 'judge/student/student_assignment.html', {'form' : form})
SyntaxError: 'return' outside function
Unhandled exception in thread started by <function wrapper at 0x7f557d12a488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 4, in <module>
    from judge.views import *
  File "/Capstone_Design/src/Django/scode/judge/views.py", line 52
    return render(request, 'judge/student/student_assignment.html')
SyntaxError: 'return' outside function
[18/May/2019 14:30:38] "GET /judge/student/std_assign HTTP/1.1" 200 1758
[18/May/2019 14:35:10] "GET /judge/student/std_assign HTTP/1.1" 200 1758
[18/May/2019 14:35:10] "GET /static/img/hallym_logo.png HTTP/1.1" 304 0
[18/May/2019 14:35:10] "GET /static/css/base.css HTTP/1.1" 304 0
[18/May/2019 14:35:11] "GET /judge/student/std_assign HTTP/1.1" 200 1758
Invalid HTTP_HOST header: '210.115.229.133:80'. You may need to add u'210.115.229.133' to ALLOWED_HOSTS.
[18/May/2019 14:37:30] "GET / HTTP/1.1" 400 58838
[18/May/2019 14:38:00] "GET /judge/student/std_assign HTTP/1.1" 200 1732
[18/May/2019 14:38:00] "GET /judge/student/std_assign HTTP/1.1" 200 1732
[18/May/2019 14:38:00] "GET /judge/student/std_assign HTTP/1.1" 200 1732
[18/May/2019 14:38:01] "GET /judge/student/std_assign HTTP/1.1" 200 1732
[18/May/2019 14:40:17] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:40:18] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:40:18] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:40:19] "GET /judge/student/std_subject HTTP/1.1" 200 1557
[18/May/2019 14:40:20] "GET /judge/student/ HTTP/1.1" 200 1551
[18/May/2019 14:40:21] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:40:22] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:40:58] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:40:58] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:41:40] "GET / HTTP/1.1" 200 1705
[18/May/2019 14:41:45] "GET /judge/student/std_subject HTTP/1.1" 200 1557
[18/May/2019 14:41:48] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:44:49] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:44:50] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:44:50] "GET /judge/student/std_assign HTTP/1.1" 200 1703
[18/May/2019 14:44:50] "GET /judge/student/std_assign HTTP/1.1" 200 1703
Unhandled exception in thread started by <function wrapper at 0x7fe3416b5488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 4, in <module>
    from judge.views import *
  File "/Capstone_Design/src/Django/scode/judge/views.py", line 5, in <module>
    from judge.forms import CodingForm
ImportError: cannot import name CodingForm
Unhandled exception in thread started by <function wrapper at 0x7f6e47c4f488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 4, in <module>
    from judge.views import *
  File "/Capstone_Design/src/Django/scode/judge/views.py", line 5, in <module>
    from judge.forms import CodingForm
ImportError: cannot import name CodingForm
[18/May/2019 14:53:43] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:53:46] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:54:37] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:54:38] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:55:07] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:55:08] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:55:08] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:55:09] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:59:30] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:59:30] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:59:30] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 14:59:34] "GET /judge/student/ HTTP/1.1" 200 1551
[18/May/2019 14:59:36] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 15:04:01] "GET /judge/student/std_assign HTTP/1.1" 200 1708
[18/May/2019 15:04:02] "GET /judge/student/std_assign HTTP/1.1" 200 1708
Unhandled exception in thread started by <function wrapper at 0x7fd07fcec488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 37, in <module>
    url(r'^student/std_assign$', Coding.as_view(), name='std_assign'),
AttributeError: 'function' object has no attribute 'as_view'
Unhandled exception in thread started by <function wrapper at 0x7f62abf35488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 4, in <module>
    from judge.views import *
  File "/Capstone_Design/src/Django/scode/judge/views.py", line 6, in <module>
    from judge.forms import Coding
ImportError: cannot import name Coding
Unhandled exception in thread started by <function wrapper at 0x7f34cb3c9488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 4, in <module>
    from judge.views import *
  File "/Capstone_Design/src/Django/scode/judge/views.py", line 6, in <module>
    from judge.forms import Coding
ImportError: cannot import name Coding
Unhandled exception in thread started by <function wrapper at 0x7fe0ec5fe488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 4, in <module>
    from judge.views import *
  File "/Capstone_Design/src/Django/scode/judge/views.py", line 6, in <module>
    from judge.forms import Coding
ImportError: cannot import name Coding
Unhandled exception in thread started by <function wrapper at 0x7f761622a488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 37, in <module>
    url(r'^student/std_assign$', Coding.as_view(), name='std_assign'),
AttributeError: 'function' object has no attribute 'as_view'
Unhandled exception in thread started by <function wrapper at 0x7f15663c2488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 37, in <module>
    url(r'^student/std_assign$', views.Coding, name='std_assign'),
NameError: name 'views' is not defined
Unhandled exception in thread started by <function wrapper at 0x7fadaa5d4488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 36, in <module>
    url(r'^student/std_assign$', views.Coding, name='std_assign'),
NameError: name 'views' is not defined
[18/May/2019 15:12:42] "GET /judge/student/std_assign HTTP/1.1" 200 1840
Internal Server Error: /judge/student/std_assign
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view judge.views.Coding didn't return an HttpResponse object. It returned None instead.
[18/May/2019 15:13:02] "POST /judge/student/std_assign HTTP/1.1" 500 55111
Unhandled exception in thread started by <function wrapper at 0x7fa8eb22f488>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/scode/urls.py", line 24, in <module>
    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Capstone_Design/src/Django/scode/judge/urls.py", line 3, in <module>
    from judge.views import *
  File "/Capstone_Design/src/Django/scode/judge/views.py", line 54
    else:
       ^
SyntaxError: invalid syntax
[18/May/2019 15:39:12] "POST /judge/student/std_assign HTTP/1.1" 200 1891
[18/May/2019 15:39:19] "GET /judge/student/std_assign HTTP/1.1" 200 1852
[18/May/2019 15:40:41] "GET /judge/student/std_assign HTTP/1.1" 200 1871
[18/May/2019 15:40:43] "GET /judge/student/std_assign HTTP/1.1" 200 1871
[18/May/2019 15:40:44] "GET /judge/student/std_assign HTTP/1.1" 200 1871
[18/May/2019 15:42:32] "GET /judge/student/std_assign HTTP/1.1" 200 1893
[18/May/2019 15:42:33] "GET /judge/student/std_assign HTTP/1.1" 200 1893
[18/May/2019 15:43:45] "GET /judge/student/std_assign HTTP/1.1" 200 1905
[18/May/2019 15:43:46] "GET /judge/student/std_assign HTTP/1.1" 200 1905
Invalid HTTP_HOST header: '210.115.229.133:80'. You may need to add u'210.115.229.133' to ALLOWED_HOSTS.
[18/May/2019 15:56:09] "GET / HTTP/1.1" 400 58850
[18/May/2019 15:58:23] "GET /judge/student/std_assign HTTP/1.1" 200 1905
[18/May/2019 16:18:58] "GET /judge/student/std_assign HTTP/1.1" 200 460
[18/May/2019 16:28:23] "GET /judge/student/std_assign HTTP/1.1" 200 462
[18/May/2019 16:29:02] "GET /judge/student/std_assign HTTP/1.1" 200 462
[18/May/2019 16:33:26] "GET /judge/student/std_assign HTTP/1.1" 200 520
